name: Deploy SimGBS site to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write  # allows pushing to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- 1. Check out the source branch (master) ---
      - name: Checkout master
        uses: actions/checkout@v4

      # --- 2. Build the publishable site directory ---
      - name: Build site directory
        run: |
          set -eux

          # Create the site directory
          mkdir site

          # (A) Homepage - use README as index
          cp README.md site/index.md

          # (B) Tutorials - copy all HTML tutorials
          mkdir -p site/tutorials
          cp tutorials/*.html site/tutorials/ || true

          # (C) Optional assets (uncomment if needed)
          # cp -r assets site/assets || true
          # cp -r css site/css || true

          # Auto-generate a simple tutorial index
          cat > site/tutorials/index.md <<'EOF'
          # Tutorials

          - [SimGBS in R via JuliaCall](SimGBS_R_JuliaCall.html)

          *(Auto-generated by GitHub Action)*
          EOF

      # --- 3. Deploy to gh-pages ---
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
