name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write    # needed so we can push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # keep history (useful for Documenter versioning, etc.)

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          # use the Julia version you want the docs built under
          version: '1.10'

      - name: Instantiate docs environment
        working-directory: docs
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.develop(PackageSpec(path = ".."))  # make sure docs can `using SimGBS`
            Pkg.instantiate()
          '

      - name: Build documentation (Documenter.jl)
        working-directory: docs
        env:
          # Let Documenter.jl know about GitHub authentication for deploying versions, etc.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project=. make.jl

      - name: Add extra tutorials / static HTML pages
        run: |
          # Make a tutorials subdir in the built docs
          mkdir -p docs/build/tutorials

          # Copy any hand-written HTML tutorials (R/JuliaCall walkthrough etc.)
          # Adjust paths if your tutorial file lives somewhere else.
          if [ -f tutorials/SimGBS_R_JuliaCall.html ]; then
            cp tutorials/SimGBS_R_JuliaCall.html docs/build/tutorials/
          fi

          # You can copy more custom pages here if you want:
          # cp tutorials/*.html docs/build/tutorials/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build
          force_orphan: false   # keep commit history on gh-pages
          # cname: your.custom.domain  # <-- only if you use a custom domain, otherwise leave out
